Repository donggyunhuh/TeamProjectFlower_Sourcecode, pull requests merged in 2023-11, with the labels that each got.

#108 폰트 적용 위치 변경
  src/main/resources/static/front/recommend/css/style.css
Labels: bug

#113 front 키워드 선택 부분 css 수정 중
  src/main/resources/static/front/recommend/css/style.css
  src/main/resources/static/front/recommend/js/common.js
  src/main/resources/templates/front/recommend/main.html
Labels: enhancement, question

#133 Daeyoon
  pom.xml
  src/main/java/org/flower/configs/SecurityConfig.java
  src/main/java/org/flower/controllers/postCard/OpenAIController.java
  src/main/java/org/flower/models/postCard/OpenAIService.java
  src/main/resources/application.properties
  src/main/resources/templates/front/main/index.html
  src/main/resources/templates/front/postcard/main.html
Labels: bug, documentation, enhancement

#137 postcard 부분 간단한 css
  src/main/resources/application.properties
  src/main/resources/static/front/postcard/css/style.css
  src/main/resources/static/front/postcard/js/common.js
  src/main/resources/templates/front/layouts/main.html
  src/main/resources/templates/front/postcard/result.html
Labels: enhancement

#140 Update README.md
  README.md
Labels: documentation, good first issue

#142 꽃 선택 옵션 th:each문으로 수정
  src/main/java/org/flower/controllers/order/OrderprocessController.java
  src/main/resources/static/front/order/js/common.js
  src/main/resources/templates/front/order/orderForm.html
Labels: UI

#160 주문서 양식, footer수정
  src/main/resources/static/front/css/style.css
  src/main/resources/static/front/order/css/style.css
  src/main/resources/templates/front/order/orderForm.html
Labels: UI

#162 주문서폼 UI변경
  src/main/resources/static/front/order/css/style.css
  src/main/resources/templates/front/order/orderForm.html
Labels: UI

#163 주문서 폼 제출 전 필수 입력 항목 검증 기능 개선
  src/main/resources/static/front/order/js/common.js
  src/main/resources/templates/front/order/orderForm.html
Labels: bug

#164 UI 자잘한 수정
  src/main/resources/static/front/order/css/style.css
  src/main/resources/templates/front/order/orderCompleted.html
  src/main/resources/templates/front/postcard/main.html
Labels: UI
